### ISSUE TITLE
The HTML report does not show test steps if we parameterize endpoint url

### ISSUE THREAD

**Issue by guptapranay** [iamakshayshar/SoapUI-Extentter#14]
The report does not show all test steps (REST/SOAP steps), if we parameterize endpoint URL in test suites. Ex: Endpoint in REST STEP parameterized as : ${#TestSuite#EndpointURL}.

The report only shows non REST/SOAP steps.

Could you please check?

**Comment by iamakshayshar** [comment]
This is to be checked and confirm. I will look into this.

**Comment by iamakshayshar** [comment]
Thank you @guptapranay for this defect. This is fixed in the latest release. 
[](url)https://github.com/iamakshayshar/SoapUI-Extentter/releases/tag/Extentter-v4.2

Also please note that the property name for the endpoint should always be "**Endpoint**" on all the levels, 
eg. 
for Project : ${#Project#**Endpoint**}
for TestSuite : ${#TestSuite#**Endpoint**}
for TestCase: ${#TestCase#**Endpoint**}

**Comment by guptapranay** [comment]
Thanks. That was pretty fast. Tried with recent fix and its woring. It also works if I give endpoint as ${#Project#EndpointURL}

**Comment by iamakshayshar** [comment]
Thank you. 
You can explore SoapuiExttenter Pro version for few other capabilities. Email me for further details.
